FROM ubuntu:22.04@sha256:b492494d8e0113c4ad3fe4528a4b5ff89faa5331f7d52c5c138196f69ce176a6 

RUN apt-get update
RUN apt-get install docker.io socat python3 python3-pip -y
RUN pip3 install docker

COPY wrapper_start.sh /
COPY shell.py /
EXPOSE 9002

ENTRYPOINT ["/wrapper_start.sh"]

