services:
  wrapper:
    build:
      context: .
      dockerfile: Dockerfile_wrapper
    ports:
      - 12006:12006
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - systempaths=unconfined
  chall:
    build:
      context: .
      dockerfile: Dockerfile_chall

