FROM python:3.10-slim as builder
RUN pip install pycryptodome

FROM pwn.red/jail
COPY --from=builder / /srv

COPY chall.py /srv/app/run
ENV JAIL_ENV_flag="EPFL{not_the_flag}"
ENV JAIL_TIME=1800
ENV JAIL_ENV_PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV JAIL_MEM 100M
RUN chmod 755 /srv/app/run
